apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: test-1
data:
  prometheus.rules: |-
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:9090']
      - job_name: 'featureform-service-monitoring'
        scrape_interval: 10s
        metrics_path: /metrics
        static_configs:
          - targets: [ "feature-server.test-1.svc.cluster.local:2112","feature-server.test-1:2112"]
