apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: feature-server
spec:
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 2112
      protocol: TCP
      targetPort: 2112
  selector:
    run: feature-server
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: feature-server
  name: feature-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: feature-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: feature-server
    spec:
      containers:
        - image: sami1309/feature-service:latest
          name: feature-server
          ports:
            - containerPort: 8080
            - containerPort: 2112
          resources: {}
status: {}
